#!/bin/bash
set -e

# ─────────────────────────────────────────────
# Vizoure NMS - Linux Agent Build Script
# Builds rebranded Zabbix agent from source
# ─────────────────────────────────────────────

source /root/vizoure-nms-builde/branding/branding.conf

ZABBIX_SOURCE="/root/vizoure-nms-builde/zabbix-source"
BUILD_DIR="/root/vizoure-nms-builde/build/linux"
PACKAGE_DIR="/root/vizoure-nms-builde/packages/linux"

mkdir -p "$BUILD_DIR" "$PACKAGE_DIR"

echo "=== Building Vizoure Agent for Linux ==="

# ─────────────────────────────────────────────
# 1. BOOTSTRAP + CONFIGURE
# ─────────────────────────────────────────────
echo "[1/5] Bootstrapping source..."
cd "$ZABBIX_SOURCE"

if [ ! -f configure ]; then
    ./bootstrap.sh
fi

./configure \
    --prefix=/usr \
    --sysconfdir=/etc/vizoure \
    --enable-agent \
    --with-openssl \
    --with-libpcre

# ─────────────────────────────────────────────
# 2. COMPILE
# ─────────────────────────────────────────────
echo "[2/5] Compiling agent..."
make -j$(nproc) src/zabbix_agent/zabbix_agentd

# ─────────────────────────────────────────────
# 3. RENAME BINARY
# ─────────────────────────────────────────────
echo "[3/5] Renaming binary..."
mkdir -p "$BUILD_DIR/usr/sbin"
mkdir -p "$BUILD_DIR/etc/vizoure"
mkdir -p "$BUILD_DIR/var/log/vizoure"
mkdir -p "$BUILD_DIR/lib/systemd/system"

# Copy and rename binary
cp src/zabbix_agent/zabbix_agentd "$BUILD_DIR/usr/sbin/vizoure_agentd"
chmod 755 "$BUILD_DIR/usr/sbin/vizoure_agentd"

# ─────────────────────────────────────────────
# 4. CREATE CONFIG FILE
# ─────────────────────────────────────────────
echo "[4/5] Creating config file..."
cat > "$BUILD_DIR/etc/vizoure/vizoure_agentd.conf" << 'CONFEOF'
# Vizoure NMS Agent Configuration
# Generated by Vizoure NMS Builder

PidFile=/var/run/vizoure/vizoure_agentd.pid
LogFile=/var/log/vizoure/vizoure_agentd.log
LogFileSize=10
Server=127.0.0.1
ServerActive=127.0.0.1
Hostname=Vizoure server
CONFEOF

# ─────────────────────────────────────────────
# 4B. CREATE SYSTEMD SERVICE
# ─────────────────────────────────────────────
cat > "$BUILD_DIR/lib/systemd/system/vizoure-agent.service" << 'SVCEOF'
[Unit]
Description=Vizoure NMS Agent
After=network.target

[Service]
Type=forking
PIDFile=/var/run/vizoure/vizoure_agentd.pid
ExecStart=/usr/sbin/vizoure_agentd -c /etc/vizoure/vizoure_agentd.conf
ExecStop=/bin/kill -SIGTERM $MAINPID
Restart=on-failure
RestartSec=5s
User=vizoure
Group=vizoure

[Install]
WantedBy=multi-user.target
SVCEOF

# ─────────────────────────────────────────────
# 5. BUILD .DEB PACKAGE
# ─────────────────────────────────────────────
echo "[5/5] Building .deb package..."

mkdir -p "$BUILD_DIR/DEBIAN"

# Package metadata
cat > "$BUILD_DIR/DEBIAN/control" << DEBEOF
Package: vizoure-agent
Version: ${BRAND_VERSION}
Architecture: amd64
Maintainer: ${BRAND_COMPANY}
Description: Vizoure NMS Agent
 Monitoring agent for Vizoure NMS.
 Collects system metrics and sends to Vizoure server.
Homepage: ${BRAND_URL}
Section: net
Priority: optional
DEBEOF

# Post-install script
cat > "$BUILD_DIR/DEBIAN/postinst" << 'POSTEOF'
#!/bin/bash
set -e
# Create user/group if not exists
if ! id -u vizoure &>/dev/null; then
    useradd -r -s /sbin/nologin -d /var/lib/vizoure vizoure
fi
mkdir -p /var/run/vizoure /var/log/vizoure
chown vizoure:vizoure /var/run/vizoure /var/log/vizoure
systemctl daemon-reload
systemctl enable vizoure-agent
systemctl start vizoure-agent
POSTEOF
chmod 755 "$BUILD_DIR/DEBIAN/postinst"

# Pre-remove script
cat > "$BUILD_DIR/DEBIAN/prerm" << 'PREREMEOF'
#!/bin/bash
set -e
systemctl stop vizoure-agent 2>/dev/null || true
systemctl disable vizoure-agent 2>/dev/null || true
PREREMEOF
chmod 755 "$BUILD_DIR/DEBIAN/prerm"

# Build the package
dpkg-deb --build "$BUILD_DIR" "$PACKAGE_DIR/vizoure-agent_${BRAND_VERSION}_amd64.deb"

echo ""
echo "========================================="
echo "  Linux Agent Build Complete!"
echo "  Package: $PACKAGE_DIR/vizoure-agent_${BRAND_VERSION}_amd64.deb"
echo "  Install:  dpkg -i vizoure-agent_${BRAND_VERSION}_amd64.deb"
echo "========================================="
